### ISSUE TITLE
[dev] Load weights from pretrained models

### ISSUE THREAD

**Issue by nickvazz** [jhchang/DFDC#1]
# Code to load pre-trained weights (I think)

```python
import torch
from torch.utils.model_zoo import load_url
import matplotlib.pyplot as plt
from scipy.special import expit

import sys
sys.path.append('..')

from blazeface import FaceExtractor, BlazeFace, VideoReader
from architectures import fornet,weights
from isplutils import utils

"""
Choose an architecture between
- EfficientNetB4
- EfficientNetB4ST
- EfficientNetAutoAttB4
- EfficientNetAutoAttB4ST
- Xception
"""
net_model = 'EfficientNetAutoAttB4'

"""
Choose a training dataset between
- DFDC
- FFPP
"""
train_db = 'DFDC'

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')
face_policy = 'scale'
face_size = 224
frames_per_video = 32

model_url = weights.weight_url['{:s}_{:s}'.format(net_model,train_db)]
net = getattr(fornet,net_model)().eval().to(device)
net.load_state_dict(load_url(model_url,map_location=device,check_hash=True))
```

**Comment by nickvazz** [comment]
might need to use a different `sys.path.append(....)` depending on how you decide to run this and from where

**Comment by nickvazz** [comment]
Might be able to get away with
```python
import torch
from torch.utils.model_zoo import load_url
from architectures import fornet, weights

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

net_model = "model of interest"
weight_url = weights.weight_url["weights of interest"]

net = getattr(fornet, net_model)().eval().to(device)
net.load_state_dict(load_url(model_url, map_location=device, check_hash=True))
```

where models are:
- `EfficientNetB4`
- `EfficientNetB4ST`
- `EfficientNetAutoAttB4`
- `EfficientNetAutoAttB4ST`
- `Xception`

and model urls are the keys of this dict: (model + either `_DFDC` or `_FFPP`)
https://github.com/jhchang/icpr2020dfdc/blob/19f66a6d4ce486f18cb182a07266851840969716/architectures/weights.py#L13-L24

**Comment by nickvazz** [comment]
@jhchang Able to use this with #9 yet?

**Comment by jhchang** [comment]
I am currently attempting to figure out how to call and run a notebook from a python file. I may just convert the notebook into a regular python file if I can't figure it out.

**Comment by nickvazz** [comment]
There is a way to convert the notebook to a file directly in the menus of the notebook. It’s possible to call a notebook from python but would require a little different way of approaching it (using `papermill` library requiring adding tags to the Jupyter notebook cells)

**Comment by jhchang** [comment]
I just converted the notebook into a .py file. I think I managed to use cli.py and pass in arguments through the cmd line to specify the model type. Then cli.py executes the converted nb. I think I still am having trouble with the nb running slowly and incorrectly.

**Comment by jhchang** [comment]
I have not integrated mlflow with this cli.py yet.

**Comment by nickvazz** [comment]
I think you would call functions rather than the notebook from the CLI

**Comment by nickvazz** [comment]
Slowly / incorrectly how?

**Comment by jhchang** [comment]
> I think you would call functions rather than the notebook from the CLI

Yeah I turned the notebook into a .py in one large function and called it from cli.py

**Comment by jhchang** [comment]
> Slowly / incorrectly how?

Just like last week. Weights/models take forever to load and the face selector doesn't extract faces. Now that my cli somewhat works, I'm trying to diagnose this issue.
