### ISSUE TITLE
[dev] get model size from pytroch

### ISSUE THREAD

**Issue by nickvazz** [jhchang/DFDC#22]
https://stackoverflow.com/a/56762410

**Comment by nickvazz** [comment]
https://github.com/sksq96/pytorch-summary

```bash
!pip install torchsummary
```

**Comment by nickvazz** [comment]
```python
from torchsummary import summary
summary(net, input_size=faces_t.shape)     
summary(net, input_size=faces_t.size)     
```

**Comment by nickvazz** [comment]
https://github.com/sksq96/pytorch-summary/blob/345d898d84507b848e92dab4629e03405e19afce/torchsummary/torchsummary.py#L9

https://github.com/sksq96/pytorch-summary/blob/345d898d84507b848e92dab4629e03405e19afce/torchsummary/torchsummary.py#L17

**Comment by nickvazz** [comment]
```python
from torchsummary import summary_string

summary_str, (total_params, trainable_params) = summary_string(net, input_size=faces_t.shape)

total_params = float(results_str.split("Total params")[-1].split("\n")[0].strip())
```
# then do the same thing for each of these

- Trainable params:
- Non-trainable params:
- Input size (MB):
- Forward/backward pass size (MB):
- Params size (MB):
- Estimated Total Size (MB):

**Comment by nickvazz** [comment]
https://github.com/sksq96/pytorch-summary/blob/master/torchsummary/tests/unit_tests/torchsummary_test.py#L2

**Comment by jhchang** [comment]
![image](https://user-images.githubusercontent.com/8294705/118347316-325fe800-b4f7-11eb-9dfd-2182036fd0c0.png)

**Comment by nickvazz** [comment]
```python
import torchsummary
print(dir(torchsummary))
```

**Comment by jhchang** [comment]
```python
['OrderedDict', 'Variable', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'nn', 'np', 'summary', 'torch']
```

**Comment by nickvazz** [comment]
```python
import io
from contextlib import redirect_stdout

f = io.StringIO()
with redirect_stdout(f):
    summary(net, input_size=(3,224,224))
out = f.getvalue()

total_params = float(out.split("Total params: ")[-1].split("\n")[0].strip().replace(',',''))
print(total_params)
```

**Comment by jhchang** [comment]
![image](https://user-images.githubusercontent.com/8294705/118347458-61c32480-b4f8-11eb-905d-fbb60a2f46e4.png)

**Comment by jhchang** [comment]
17550466.0

**Comment by nickvazz** [comment]
https://github.com/jhchang/DFDC/issues/22#issuecomment-841594655

**Comment by nickvazz** [comment]
> 17550466.0 https://github.com/jhchang/DFDC/issues/22#issuecomment-841596275

Closing since we figured it out
