### ISSUE TITLE
[dev] find out how to prune weights using pytorch

### ISSUE THREAD

**Issue by nickvazz** [jhchang/DFDC#4]
https://pytorch.org/tutorials/intermediate/pruning_tutorial.html

**Comment by jhchang** [comment]
I think I'm going to try the global pruning section of that tutorial.

**Comment by jhchang** [comment]
Main steps:
1) load modules of the model into a iterable
2) call prune.global_unstructured on the model
2.1) prune weights and bias of a permutation of modules and test to see which gives me the best results.
2.2) calculate which layers are pruned the most based on the pytorch tutorial.
3) put the modules back into the model
4) save model and compare how much the size difference
5) during testing take time diagnostics to see how much faster the model runs

**Comment by nickvazz** [comment]
![image](https://user-images.githubusercontent.com/8573886/118345671-fb83d500-b4ea-11eb-8355-94b6af1be266.png)

**Comment by nickvazz** [comment]
https://pytorch.org/docs/stable/nn.html#utilities

**Comment by jhchang** [comment]
# of Params to be pruned: 420
% param pruned: 0.4
Files tested: ['aagfhgtpmv.mp4' 'acqfdwsrhi.mp4' 'abarnvbtwb.mp4' 'acxwigylke.mp4']
Predicted Scores [0.7428364, 0.90005845, 0.20167673, 0.91815364]
Rounded Predicted Scores[1 1 0 1]
Real Scores [1 1 0 1]
Accuracy: 1.0
Runtime 0.22300267219543457
==================================================
Files tested: ['aelfnikyqj.mp4' 'aczrgyricp.mp4' 'abofeumbvv.mp4' 'abqwwspghj.mp4']
Predicted Scores [0.3389638, 0.8175812, 0.58836764, 0.9106489]
Rounded Predicted Scores[0 1 1 1]
Real Scores [0 1 1 1]
Accuracy: 1.0
Runtime 0.22330331802368164
==================================================
Files tested: ['acifjvzvpm.mp4' 'acxnxvbsxk.mp4' 'aapnvogymq.mp4' 'adhsbajydo.mp4']
Predicted Scores [0.63738626, 0.9189092, 0.6444868, 0.5847011]
Rounded Predicted Scores[1 1 1 1]
Real Scores [1 1 1 1]
Accuracy: 1.0
Runtime 0.2230052947998047
==================================================
Files tested: ['afoovlsmtx.mp4' 'ajqslcypsw.mp4' 'agrmhtjdlk.mp4' 'ahqqqilsxt.mp4']
Predicted Scores [0.24079886, 0.21363088, 0.44002277, 0.3177779]
Rounded Predicted Scores[0 0 0 0]
Real Scores [0 0 0 0]
Accuracy: 1.0
Runtime 0.22284269332885742
==================================================
Files tested: ['anpuvshzoo.mp4' 'atvmxvwyns.mp4' 'atkdltyyen.mp4' 'asaxgevnnp.mp4']
Predicted Scores [0.37423393, 0.5255266, 0.16300006, 0.37184343]
Rounded Predicted Scores[0 1 0 0]
Real Scores [0 0 0 0]
Accuracy: 0.75
Runtime 0.22306203842163086
==================================================
# of Params to be pruned: 420
% param pruned: 0.4
Files tested: ['aagfhgtpmv.mp4' 'acqfdwsrhi.mp4' 'abarnvbtwb.mp4' 'acxwigylke.mp4']
Predicted Scores [0.7428364, 0.90005845, 0.20167673, 0.91815364]
Rounded Predicted Scores[1 1 0 1]
Real Scores [1 1 0 1]
Accuracy: 1.0
Runtime 0.2232959270477295
==================================================
Files tested: ['aelfnikyqj.mp4' 'aczrgyricp.mp4' 'abofeumbvv.mp4' 'abqwwspghj.mp4']
Predicted Scores [0.3389638, 0.8175812, 0.58836764, 0.9106489]
Rounded Predicted Scores[0 1 1 1]
Real Scores [0 1 1 1]
Accuracy: 1.0
Runtime 0.22216057777404785
==================================================
Files tested: ['acifjvzvpm.mp4' 'acxnxvbsxk.mp4' 'aapnvogymq.mp4' 'adhsbajydo.mp4']
Predicted Scores [0.63738626, 0.9189092, 0.6444868, 0.5847011]
Rounded Predicted Scores[1 1 1 1]
Real Scores [1 1 1 1]
Accuracy: 1.0
Runtime 0.22339344024658203
==================================================
Files tested: ['afoovlsmtx.mp4' 'ajqslcypsw.mp4' 'agrmhtjdlk.mp4' 'ahqqqilsxt.mp4']
Predicted Scores [0.24079886, 0.21363088, 0.44002277, 0.3177779]
Rounded Predicted Scores[0 0 0 0]
Real Scores [0 0 0 0]
Accuracy: 1.0
Runtime 0.22297406196594238
==================================================
Files tested: ['anpuvshzoo.mp4' 'atvmxvwyns.mp4' 'atkdltyyen.mp4' 'asaxgevnnp.mp4']
Predicted Scores [0.37423393, 0.5255266, 0.16300006, 0.37184343]
Rounded Predicted Scores[0 1 0 0]
Real Scores [0 0 0 0]
Accuracy: 0.75
Runtime 0.222306489944458
==================================================

**Comment by jhchang** [comment]
Params to be pruned: 420
% param pruned: 0.4
Files tested: ['aagfhgtpmv.mp4' 'acqfdwsrhi.mp4' 'abarnvbtwb.mp4' 'acxwigylke.mp4']
Predicted Scores [0.7428364, 0.90005845, 0.20167673, 0.91815364]
Rounded Predicted Scores[1 1 0 1]
Real Scores [1 1 0 1]
Accuracy: 1.0
Runtime 0.22300267219543457


Params to be pruned: 420
% param pruned: 0.4
Files tested: ['aagfhgtpmv.mp4' 'acqfdwsrhi.mp4' 'abarnvbtwb.mp4' 'acxwigylke.mp4']
Predicted Scores [0.7428364, 0.90005845, 0.20167673, 0.91815364]
Rounded Predicted Scores[1 1 0 1]
Real Scores [1 1 0 1]
Accuracy: 1.0
Runtime 0.2232959270477295
